# Drops existing tables, recreates them and executes import.sql
spring:
    jpa:
        hibernate:
            ddl-auto: update
        naming:
            physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
            implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate:
                proc.param_null_passing: true
            show-sql: true
            database-platform: org.hibernate.dialect.Oracle10gDialect
            
# Settings for the oracle connection
    datasource:
        jdbc-url:
            jdbc:oracle:thin:@172.16.32.135:1521:orcl
            #jdbc:oracle:thin:@localhost:1521:orcl
        username:
            content
        password:
            content2012
        driver-class-oracle:
            jdbc:
                driver:
                    OracleDriver
        type: com.zaxxer.hikari.HikariDataSource
        # Hikari
        poolName: SpringBootHikariIntergrade
        maximumPoolSize: 5
        minimumIdle: 3
        maxLifetime: 2000000
        connectionTimeout: 30000
        idleTimeout: 30000
        pool-prepared-statements: true
        max-open-prepared-statements: 250
        connection-test-query: SELECT 1 FROM DUAL
management:
  security:
    enabled: false
security:
  basic:
    enabled: false